version: '3.7'

services:
  app:
    build: .
    container_name: rails_with_docker
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge