default: &default  
  adapter: postgresql  
  encoding: unicode  
  pool: 5  
  username: postgres  
  password: 123456  
  host: db  # This matches the service name of your PostgreSQL container in docker-compose.yml
  port: 5432

development:  
  <<: *default  
  database: rails_with_docker_development  

test:  
  <<: *default  
  database: rails_with_docker_development  

production:  
  <<: *default  
  database: your_app_production  
  username: <%= ENV['DATABASE_USERNAME'] %>  
  password: <%= ENV['DATABASE_PASSWORD'] %>